# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# Define the type of board to compile for.  Some boards (i.e. mega) require an
# additional define of a BOARD_SUB.
# Do a 'make show_boards' to see possible board tags.

# For Mega 2560
# BOARD_TAG    = mega
# BOARD_SUB    = atmega2560

# For Uno
BOARD_TAG	 = uno

# Define the serial port name to upload to the Arduino
MONITOR_PORT = /dev/cu.usbmodem1421

include ../Arduino-Makefile/Arduino.mk
